### ISSUE TITLE
Per-domain language set configuration

### ISSUE THREAD

**Issue by artreaktor** [agentrickard/domain#196]
Sould it be the domain_config part, or standalone module?

**Comment by agentrickard** [comment]
I don't understand the question. We already have per-language configuration in Domain Config, and there is already an issue to add a UI for that. #15 

The UI would be part of Domain Config. It's the last Alpha blocker because it may require API changes.

**Comment by artreaktor** [comment]
Dumb question, sorry... But I have another one:
How to override config with *.yml in custom module?
I'm asking because I'm unable to override nothing:
1. I created custom my_exaple_config module in 
modules/my_example/my_exaple_config
2. added config file under
config/install
  domain.config.one_example_com.system.site.yml
3. enabled new module
That's what I have in the config inspection screen:
![domain_config](https://cloud.githubusercontent.com/assets/1705475/13187988/52b3f0e8-d757-11e5-9775-ddec96ef870d.JPG)

Config contents:
```
uuid: cc25d990-.............-ec22d2f68ad9
name: My ONE Example Site
mail: info@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: de
default_langcode: de
_core:
  default_config_hash: yXadRE77Va..........O4oXiOEynI
```
