### ISSUE TITLE
Merge in partial config overrides instead?

### ISSUE THREAD

**Issue by nedjo** [agentrickard/domain#244]
Currently config overrides replace the full item. This can lead to unexpected or undesired outcomes.

Example:
* On domain B, register an override of ```system.site``` to customize the name per domain.
* Later, edit the original ```system.site.page.404``` value. The edit is not carried through to Domain B, since, to override the name, all ```system.site``` values were overridden.

An alternative would be to adopt the approach used in the [Config Override](https://www.drupal.org/project/config_override) module, where partial overrides are merged in. See [ModuleConfigOverrides](http://cgit.drupalcode.org/config_override/tree/src/ModuleConfigOverrides.php).

**Comment by agentrickard** [comment]
Can you export partial config yml files like that? Won't they break on import because of missing schema?

**Comment by agentrickard** [comment]
Oh, I see what that module is doing. It seems to be bypassing the core import/export model, which is what we're using now.

That would be a paradigm shift in how we think about config.

Another option: I wonder if we could use a placeholder definition in the yml output to indicate "inherit from the default config"?

Something like so:

```
name: 'Four'
mail: admin@example.com
slogan: '*INHERIT*'
page:
  403: '*INHERIT*'
  404: '*INHERIT*'
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
langcode: en
```
