### ISSUE TITLE
Move to testing Drupal 8.4 and 8.5

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#372]
Automated testing will move the 8.4 and 8.5.

Development will proceed against 8.5-dev pending successful tests.

**Comment by agentrickard** [comment]
Drupal 8.5 does not support PHP 5.5 and 5.6. 

@zerolab I may need some help customizing the Travis build.

**Comment by zerolab** [comment]
Change https://github.com/agentrickard/domain/blob/8.x-1.x/.travis.yml#L4
to `php: [7.0, 7.1]` ?

although 8.4 supports them. will have a think at home and provide patch

**Comment by agentrickard** [comment]
The tests are all green, so perhaps we don't have to do anything right now.

https://travis-ci.org/agentrickard/domain/builds/290528401?utm_source=github_status&utm_medium=notification

**Comment by zerolab** [comment]
Ah, just saw https://www.drupal.org/node/2842431. So 5.5/5.6 are still supported.

For future reference, I believe we'll need something like:

```yaml
matrix:
  include:
   - env: DRUPAL=8.4.x
     php: [7.0, 5.6, 5.5]
  - env: DRUPAL=8.4.x
     php: [7.0, 5.6, 5.5]
```

**Comment by agentrickard** [comment]
So we can set that up now, just so it's clear when it's really needed.  Thanks,

**Comment by agentrickard** [comment]
Giving it a try and it failed spectacularly.

https://github.com/agentrickard/domain/pull/373/commits/a75f9604ed70229aa6c013eb67a24a1314c0d66c

**Comment by zerolab** [comment]
hmm.. may have to be one php version per env. the documentation is a bit ambiguous in that regard.
Was in a bit of a rush. Moving office.

anyhow, it should be:

```
  include:
    - env: DRUPAL=8.4.x
      php: 7.0
    - env: DRUPAL=8.4.x
      php: 5.6
    - env: DRUPAL=8.4.x
      php: 5.5
    - env: DRUPAL=8.5.x
      php: 7.0
    - env: DRUPAL=8.5.x
      php: 5.6
    - env: DRUPAL=8.5.x
      php: 5.5
```
