### ISSUE TITLE
Domain Config: Different home page on each site - problem with caching

### ISSUE THREAD

**Issue by bjaxelsen** [agentrickard/domain#67]
I wish to serve different home pages for different domains (say /node/1 on domain 1 and /node/2 on domain 2).

Drupal caches the path of the home page, so doing a domain-based configuration of what page to use as a home page (system.site>page.front) is not working (though the other site settings are working fine per domain.

Of course, you can hack your way around it, but is there any way we might achieve this goal in a simple way?

As far as I can see we need a change in core to avoid this problem, but I may be missing something.

**Comment by agentrickard** [comment]
I am confused by this comment "though the other site settings are working fine per domain".

Did you get Domain Conf working just by adding the missing method from #64?

Do you have Domain Conf tests passing?

How are you changing variable settings without a UI?

To answer the question, in prior versions we relied on variable switching _before_ the cache layer was invoked. That's why you have to include code in settings.php. So we should look at the call stack and see if we can fire Domain Conf before caching is invoked.

**Comment by agentrickard** [comment]
Here's what happens when I try to run the test, even after fixing the missing method:

```
The test did not complete due to a fatal error. 	Completion check 	DomainConfigOverriderTest.php 	20 	Drupal\domain_config\Tests\DomainConfigOverriderTest->testDomainConfigOverrider() 	Fail
Drupal\Core\Config\Schema\SchemaIncompleteException: No schema for domain.config.one_example_com.system.site in Drupal\Core\Config\Testing\ConfigSchemaChecker->onConfigSave() (line 91 of /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Config/Testing/ConfigSchemaChecker.php).

Drupal\Core\Config\Testing\ConfigSchemaChecker->onConfigSave(Object, 'config.save', Object)
```

**Comment by bjaxelsen** [comment]
Yes it is actually running these two sites currently:
tegl-erfa.dk and byggedetaljer.dk (Drupal 8 beta 15)

**Comment by bjaxelsen** [comment]
For the main site I have this system.site.yml:

```
uuid: 678ae44f-9fbb-44b6-8537-5585a7b363f0
name: tegl-erfa.dk
mail: bjorn.axelsen@mydomain.dk
slogan: 'inspiration og viden om murværk'
page:
  403: ''
  404: ''
  front: /forside
admin_compact_mode: false
weight_select_max: 100
langcode: da
default_langcode: da
```

And the other will use this domain-specific confiuration in domain.config.byggedetaljer_dk.system.site.yml:
```
uuid: 342780f0-458c-11e5-9471-00259029d1aa
name: byggedetaljer.dk
mail: bjorn.axelsen@mydomain.dk
slogan: 'konstruktionsopbygninger og byggetekniske detaljer'
page:
  403: ''
  404: ''
  front: /node/297
admin_compact_mode: false
weight_select_max: 100
langcode: da
default_langcode: da
```

As mentioned, the front page setting is not working as I want it to, but site name and slogan is just fine.

In terms of editing: I created the yml manuallu and read it into DB using the Drupal 8 configuration import tool.
